import type { TranslationKey } from '@/app/lib/translations';
import type { ProjectDetail, ProjectRaw } from '@/app/types';

export const projectsRaw: ProjectRaw[] = [
  {
    id: 1,
    titleKey: 'houseOfCbTitle',
    descriptionKey: 'houseOfCbDesc',
    detailedDescriptionKey: 'houseOfCbDetailDesc',
    featuresKey: 'houseOfCbFeatures',
    challengesKey: 'houseOfCbChallenges',
    learningsKey: 'houseOfCbLearnings',
    subtitle: 'Fashion e-commerce platform',
    tech: [
      'Smarty',
      'PHP 8.5',
      'Next.js 16',
      'React 19',
      'TypeScript',
      'MySQL',
      'Tailwind CSS',
      'REST API',
      'Docker',
      'AWS',
    ],
    categoryKey: 'fullStack',
    statusKey: 'live',
    github: '',
    demo: 'https://www.houseofcb.com',
    heroImage: '/projects/hofcb/hero.png',
    images: [
      '/projects/hofcb/screenshot-1.png',
      '/projects/hofcb/screenshot-2.png',
      '/projects/hofcb/screenshot-3.png',
      '/projects/hofcb/screenshot-4.png',
    ],
    isPrivate: true,
  },{
    id: 2,
    titleKey: 'paytoTitle',
    descriptionKey: 'paytoDesc',
    detailedDescriptionKey: 'paytoDetailDesc',
    featuresKey: 'paytoFeatures',
    challengesKey: 'paytoChallenges',
    learningsKey: 'paytoLearnings',
    subtitle: 'Financial management made simple for Argentine businesses',
    tech: [
      'Laravel 12',
      'PHP 8.2',
      'Next.js 15',
      'React 19',
      'TypeScript',
      'MySQL',
      'Tailwind CSS',
      'shadcn/ui',
      'Recharts',
      'Sanctum',
      'Pest PHP',
    ],
    categoryKey: 'fullStack',
    statusKey: 'live',
    github: 'https://github.com/alefeas/payto-backend',
    githubFrontend: 'https://github.com/alefeas/payto-frontend',
    demo: 'https://payto.vercel.app',
    heroImage: '/projects/payto/hero.png',
    images: [
      '/projects/payto/screenshot-1.png',
      '/projects/payto/screenshot-2.png',
      '/projects/payto/screenshot-3.png',
      '/projects/payto/screenshot-4.png',
    ],
  },
  {
    id: 3,
    titleKey: 'hofcbAiTitle',
    descriptionKey: 'hofcbAiDesc',
    detailedDescriptionKey: 'hofcbAiDetailDesc',
    featuresKey: 'hofcbAiFeatures',
    challengesKey: 'hofcbAiChallenges',
    learningsKey: 'hofcbAiLearnings',
    subtitle: 'AI-powered luxury fashion recommendation engine',
    tech: [
      'Next.js 16',
      'React 19',
      'TypeScript',
      'Prisma',
      'MySQL',
      'Tailwind CSS',
      'Generative AI',
      'Vision Models',
      'Image Generation',
      'Nano Banana API',
    ],
    categoryKey: 'fullStack',
    statusKey: 'live',
    github: '',
    demo: '',
    heroImage: '/projects/hofcb-ai/hero.png',
    images: [
      '/projects/hofcb-ai/screenshot-1.png',
      '/projects/hofcb-ai/screenshot-2.png',
      '/projects/hofcb-ai/screenshot-3.png',
      '/projects/hofcb-ai/screenshot-4.png',
    ],
    isPrivate: true,
  },
  {
    id: 4,
    titleKey: 'bennusTitle',
    descriptionKey: 'bennusDesc',
    detailedDescriptionKey: 'bennusDetailDesc',
    featuresKey: 'bennusFeatures',
    challengesKey: 'bennusChallenges',
    learningsKey: 'bennusLearnings',
    subtitle: 'Full-stack meal delivery e-commerce platform',
    tech: [
      'Next.js 16',
      'React 19',
      'TypeScript',
      'MySQL',
      'Prisma',
      'Tailwind CSS',
      'shadcn/ui',
      'Server Actions',
    ],
    categoryKey: 'fullStack',
    statusKey: 'inDevelopment',
    github: '',
    demo: '',
    heroImage: '/projects/bennus/hero.png',
    images: [
      '/projects/bennus/screenshot-1.png',
      '/projects/bennus/screenshot-2.png',
      '/projects/bennus/screenshot-3.png',
    ],
    isPrivate: true,
  },
  {
    id: 5,
    titleKey: 'strongwoodTitle',
    descriptionKey: 'strongwoodDesc',
    detailedDescriptionKey: 'strongwoodDetailDesc',
    featuresKey: 'strongwoodFeatures',
    challengesKey: 'strongwoodChallenges',
    learningsKey: 'strongwoodLearnings',
    subtitle: 'Custom furniture and woodwork business platform',
    tech: [
      'Next.js 16',
      'React 19',
      'TypeScript',
      'Tailwind CSS',
      'Framer Motion',
      'Nodemailer',
      'SEO Optimization',
      'Responsive Design',
    ],
    categoryKey: 'frontEnd',
    statusKey: 'live',
    github: '',
    demo: 'https://www.strongwood.com.ar/',
    heroImage: '/projects/strongwood/hero.png',
    images: [
      '/projects/strongwood/screenshot-1.png',
      '/projects/strongwood/screenshot-2.png',
      '/projects/strongwood/screenshot-3.png',
      '/projects/strongwood/screenshot-4.png',
    ],
    isPrivate: true,
  },
  {
    id: 6,
    titleKey: 'airGeorgeTitle',
    descriptionKey: 'airGeorgeDesc',
    detailedDescriptionKey: 'airGeorgeDetailDesc',
    featuresKey: 'airGeorgeFeatures',
    challengesKey: 'airGeorgeChallenges',
    learningsKey: 'airGeorgeLearnings',
    subtitle: 'Automotive service site',
    tech: [
      'Next.js 15',
      'React 19',
      'TypeScript',
      'Tailwind CSS',
      'Email Integration',
      'SEO Optimization',
      'Responsive Design',
    ],
    categoryKey: 'fullStack',
    statusKey: 'live',
    github: '',
    demo: 'https://www.airgeorge.ar',
    heroImage: '/projects/air-george/hero.png',
    images: [
      '/projects/air-george/screenshot-1.png',
      '/projects/air-george/screenshot-2.png'
    ],
    isPrivate: true,
  },
];

export const getProjects = (
  t: (key: TranslationKey) => string | string[]
): ProjectDetail[] =>
  projectsRaw.map((project) => ({
    ...project,
    title: t(project.titleKey) as string,
    description: t(project.descriptionKey) as string,
    detailedDescription: t(project.detailedDescriptionKey) as string,
    features: t(project.featuresKey) as string[],
    challenges: t(project.challengesKey) as string,
    learnings: t(project.learningsKey) as string,
    category: t(project.categoryKey) as string,
    status: t(project.statusKey) as string,
    isLive: project.statusKey === 'live',
  }));
